---

- name: Make sure that system group with access to /proc exists
  group:
    name: '{{ console_proc_hidepid_group }}'
    system: True
    state: 'present'
  when: console_proc_hidepid|d()

- name: Configure /proc with hidepid= in /etc/fstab
  mount:
    name: '/proc'
    src: 'proc'
    fstype: 'proc'
    opts: 'defaults,hidepid={{ console_proc_hidepid_level }},gid={{ console_proc_hidepid_group }}'
    state: 'mounted'
  when: console_proc_hidepid|d()

  # This is a workaround for Ubuntu bug: https://bugs.launchpad.net/ubuntu/+source/mountall/+bug/1039887
- name: Remount /proc from rc.local when needed
  lineinfile:
    dest: '/etc/rc.local'
    regexp: '^mount -o remount,hidepid={{ console_proc_hidepid_level }},gid={{ console_proc_hidepid_group }} /proc'
    line: 'mount -o remount,hidepid={{ console_proc_hidepid_level }},gid={{ console_proc_hidepid_group }} /proc'
    insertbefore: 'exit 0'
    state: 'present'
  when: (console_proc_hidepid|d() and
         (ansible_distribution in [ 'Ubuntu' ] and ansible_distribution_release in [ 'trusty' ]))

- name: Create the systemd-logind configuration directory
  file:
    path: '/etc/systemd/system/systemd-logind.service.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: (console_proc_hidepid | bool and
         (ansible_local|d() and ansible_local.init|d() and
          ansible_local.init == "systemd"))

- name: Ensure that logind is exempt from hidepid
  template:
    src: 'etc/systemd/system/systemd-logind.service.d/hidepid.conf.j2'
    dest: '/etc/systemd/system/systemd-logind.service.d/hidepid.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: console_register_hidepid_logind
  when: (console_proc_hidepid | bool and
         (ansible_local|d() and ansible_local.init|d() and
          ansible_local.init == "systemd"))

- name: Reload systemd daemons
  command: systemctl daemon-reload
  when: console_register_hidepid_logind.changed | bool

